INTENTS_TEMPLATE = {
    "movie_provider": [
        "Where can I find [{movie}](movie)?",
        "Tell me where to find [{movie}](movie)",
        "Where is [{movie}](movie)?",
        "Find me [{movie}](movie)",
        "Where can I watch [{movie}](movie)?",
    ],
    "all_stars_movie": [
        "Tell me all the actors in [{movie}](movie)",
        "Who is starring in [{movie}](movie)?",
        "Who are the main actors of [{movie}](movie)?",
        "Who are the actors in [{movie}](movie)?",
        "The actors in [{movie}](movie)?",
    ],
    "movie_director": [
        "Who directed [{movie}](movie)?",
        "Who is the director of [{movie}](movie)?",
        "Tell me the director of [{movie}](movie)",
        "The director of [{movie}](movie)",
        "I want to know to know who directed [{movie}](movie)",
        "I want to know to know the director of [{movie}](movie)",
    ],
    "movie_writer": [
        "Who wrote [{movie}](movie)?",
        "Who are the writers of [{movie}](movie)?",
        "Tell me the writer of [{movie}](movie)",
        "The writer of [{movie}](movie)",
        "Tell me the writers of [{movie}](movie)",
        "I want to know the writers of [{movie}](movie)",
        "I want to know to know the writer of [{movie}](movie)",
    ],
    "person_info": [
        "Tell me something about [{person}](person)",
        "Who is [{person}](person)?",
        "What can you tell me about [{person}](person)?",
        "What do you know about [{person}](person)?",
        "Tell me about [{person}](person)",
    ],
    "movie_plot": [
        "What is the plot of [{movie}](movie)",
        "Tell me something about [{movie}](movie)",
        "Tell me the plot of [{movie}](movie)",
        "What is [{movie}](movie) about?",
        "Tell me what the [{movie}](movie) is about",
    ],
    "movie_reviews": [
        "How is [{movie}](movie) rated?",
        "What are the reviews of [{movie}](movie)?",
        "What are the [{movie}](movie) reviews?",
        "Tell me how [{movie}](movie) is reviewed",
    ],
}
